import { createAsyncThunk, createSlice, PayloadAction } from '@reduxjs/toolkit'
import { RootState } from 'app/store'
import axios from 'axios'
import {CartGetState, OrderListState } from 'models/features'
import cartApi from 'api/cart-api'
import { refreshToken, selectUserDetail } from 'features/auth/user-login-slice'
import { validateToken } from 'features/validateToken'

const initialState: CartGetState = {
  cart: undefined,
  status: 'init',
  failureDescription: ''
}

// The function below is called a thunk and allows us to perform async logic. It
// can be dispatched like a regular action: `dispatch(incrementAsync(10))`. This
// will call the thunk with the `dispatch` function as the first argument. Async
// code can then be executed and other actions can be dispatched. Thunks are
// typically used to make async requests.
export const getCartAsync = createAsyncThunk(
  'cartGet/getCartAsync',
  async (data, {dispatch, getState, rejectWithValue }) => {
    try {
      // console.log('calling get orders')
      const userDetail = selectUserDetail(getState() as RootState)
      validateToken(userDetail, dispatch)
      const response = await cartApi.getLatestCartDetail(userDetail)
      return response
    } catch (error) {
      if (axios.isAxiosError(error)) {
        if (!error.response) {
          throw error
        }
        return rejectWithValue(error.response.data)
      } else {
        throw error
      }
    }
  }
)

const cartGetSlice = createSlice({
  name: 'cartGet',
  initialState,
  reducers: {
    resetCartGet: handleResetAction,
  },
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  extraReducers: (builder) => {
    builder
      .addCase(getCartAsync.pending, (state: CartGetState) => {
        return {
          cart: undefined,
          status: 'loading',
          failureDescription: '',
        }
      })
      .addCase(getCartAsync.fulfilled, (state: CartGetState, action) => {
        return {
          cart: action.payload,
          status: 'idle',
          failureDescription: ''
        }
      })
      .addCase(getCartAsync.rejected, (state: CartGetState, action) => {
        return {
          cart: undefined,
          status: 'failed',
          failureDescription: JSON.stringify(action.payload as Object),
        }
      })
  },
})

function handleResetAction(state: CartGetState) {
  state.cart = undefined
  state.status = 'init'
  state.failureDescription = ''
}

export const { resetCartGet } = cartGetSlice.actions

export const selectCart = (state: RootState) => state.cartGet.cart
export const selectCartStatus = (state: RootState) => state.cartGet.status
export const selectFailureDescription = (state: RootState) =>
  state.cartGet.failureDescription

export const cartGetReducer = cartGetSlice.reducer
